# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9156ad2b4c176e023130f8da67220cda90b2336be22fff389674a5ead3cb8208b16f82b428fc3211f354e21419f37c959f5b63fb45279be15cd6439be766eb98

test:
  secret_key_base: dd6ab3adfb00d683c08411c9b190309f75f82b322a104077e3fe46103c28fa27581d4d2cba76bfa51c954ffa256d6d74c4554c33f3cdd7ef126cb175319ea6dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
